name: datasuck
favicon: null
layout_spectrum: 0.9475343369413167
typography_spectrum: 0.12052559526637197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a242d'
    - '#3f5183'
    - '#a77b9f'
    - '#4619b6'
  brandStrength: 0.1265996927395463
  lightness: 0.39522728603333235
  saturation: 0.8134893989190459
  rhythmicContrast: 0.09114728006534278
purpose: []
